// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm010CneRzj-LJMKW36OJLF1qgtCtRsHI',
    appId: '1:1052964691730:android:7cbe315271107457b55dcb',
    messagingSenderId: '1052964691730',
    projectId: 'starwish',
    storageBucket: 'starwish.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvAYV6oGrljFJeKDpPzO1ydO6V4_rerQE',
    appId: '1:1052964691730:ios:26e2a2afa1b1c7c2b55dcb',
    messagingSenderId: '1052964691730',
    projectId: 'starwish',
    storageBucket: 'starwish.appspot.com',
    iosClientId: '1052964691730-rb480lmeqd6an8rvcpp8334pvd0prokl.apps.googleusercontent.com',
    iosBundleId: 'com.starwish.adhaar',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdDkSiBg5vDmoydgbLsLLauxRDXraZYeQ',
    appId: '1:1052964691730:web:ad00a48cd78f13b3b55dcb',
    messagingSenderId: '1052964691730',
    projectId: 'starwish',
    authDomain: 'starwish.firebaseapp.com',
    storageBucket: 'starwish.appspot.com',
    measurementId: 'G-BVRM980P0Z',
  );

}